#pragma once

#include <cstdint>

enum DIR : uint8_t {
	LEFT = 0,
	RIGHT = 1,
	BOTTOM = 2,
	TOP = 3,
	FRONT = 4,
	BACK = 5,
	ANY = 6,
};

enum BIOME_TYPE : uint8_t {
	BIOME_OCEAN = 0,
	BIOME_BEACH = 1,
	BIOME_TUNDRA = 2,
	BIOME_TAIGA = 3,
	BIOME_PLAINS = 4,
	BIOME_SWAMP = 5,
	BIOME_FOREST = 6,
	BIOME_SHRUBLAND = 7,
	BIOME_DESERT = 8,
	BIOME_RAINFOREST = 9,
	BIOME_SEASONFOREST = 10,
	BIOME_SAVANA = 11,
	BIOME_SNOWY_TAIGA = 12
};

enum BIOME_INSTANCE_COUNT_PER_CHUNK : uint32_t {
	BIOME_OCEAN_INSTANCE_COUNT = 3,
	BIOME_BEACH_INSTANCE_COUNT = 3,
	BIOME_TUNDRA_INSTANCE_COUNT = 3,
	BIOME_TAIGA_INSTANCE_COUNT = 3,
	BIOME_PLAINS_INSTANCE_COUNT = 3,
	BIOME_SWAMP_INSTANCE_COUNT = 3,
	BIOME_FOREST_INSTANCE_COUNT = 3,
	BIOME_SHRUBLAND_INSTANCE_COUNT = 3,
	BIOME_DESERT_INSTANCE_COUNT = 3,
	BIOME_RAINFOREST_INSTANCE_COUNT = 3,
	BIOME_SEASONFOREST_INSTANCE_COUNT = 3,
	BIOME_SAVANA_INSTANCE_COUNT = 3,
	BIOME_SNOWY_TAIGA_INSTANCE_COUNT = 3,
	BIOME_NONE_INSTANCE_COUNT = 0,
};

enum INSTANCE_SHAPE : uint8_t {
	INSTANCE_CROSS = 0,
	INSTANCE_FENCE = 1,
	INSTANCE_SQUARE = 2,
	INSTANCE_SHAPE_COUNT = 3,
};

enum BLOCK_TYPE : uint8_t {
	// block
	BLOCK_AIR = 0,
	BLOCK_WATER = 1,
	BLOCK_BEDROCK = 2,
	BLOCK_GRASS = 3,
	BLOCK_SNOW_GRASS = 4,
	BLOCK_DIRT = 5,
	BLOCK_STONE = 6,
	BLOCK_SAND = 7,
	BLOCK_SNOW = 8,
	BLOCK_GRAVEL = 9,
	BLOCK_SANDSTONE = 10,
	BLOCK_CLAY = 11,
	BLOCK_ANDESITE = 12,
	BLOCK_COAL_ORE = 13,
	BLOCK_GOLD_ORE = 14,
	BLOCK_REDSTONE_ORE = 15,
	BLOCK_DIAMOND_ORE = 16,
	BLOCK_COPPER_ORE = 17,
	BLOCK_IRON_ORE = 18,
	BLOCK_COARSE = 19,
	BLOCK_PODZOL = 20,
	BLOCK_ICE = 21,
	BLOCK_GOLD = 22,

	// tree
	BLOCK_LOG_OAK = 23,

	// leaves
	BLOCK_LEAVES_OAK = 48,
};

enum INSTANCE_TYPE : uint8_t {
	INSTANCE_SHORT_GRASS = 0,

};

enum TEXTURE_INDEX : uint8_t {
	// block
	TEXTURE_WATER = 0,
	TEXTURE_GRASS_TOP = 1,
	TEXTURE_GRASS_OVERLAY = 2,
	TEXTURE_DIRT = 3,
	TEXTURE_SAND = 4,
	TEXTURE_BEDROCK = 5,
	TEXTURE_STONE = 6,
	TEXTURE_SNOW_GRASS_TOP = 7,
	TEXTURE_SNOW_GRASS_SIDE = 8,
	TEXTURE_SNOW = 9,
	TEXTURE_GRAVEL = 10,
	TEXTURE_SANDSTONE_SIDE = 11,
	TEXTURE_SANDSTONE_BOTTOM = 12,
	TEXTURE_SANDSTONE_TOP = 13,
	TEXTURE_CLAY = 14,
	TEXTURE_ANDESITE = 15,
	TEXTURE_GOLD_ORE = 16,
	TEXTURE_REDSTONE_ORE = 17,
	TEXTURE_DIAMOND_ORE = 18,
	TEXTURE_COPPER_ORE = 19,
	TEXTURE_IRON_ORE = 20,
	TEXTURE_COAL_ORE = 21,
	TEXTURE_COARSE = 22,
	TEXTURE_PODZOL_TOP = 23,
	TEXTURE_PODZOL_SIDE = 24,
	TEXTURE_ICE = 25,
	TEXTURE_GOLD = 26,

	// tree
	TEXTURE_LOG_OAK = 27,
	TEXTURE_LOG_OAK_TOP = 28,

	// leaves
	TEXTURE_LEAVES_OAK = 48,

	// instance
	TEXTURE_SHORT_GRASS = 129,

	TEXTURE_NONE = 255,
};

